-- Original aggregation

SELECT CONVERT(date,ACTION_DT_TM) 'month' 
 ,UBRN_ID
 ,ACTION_CD
 ,ACTION_DESC
 ,CASE 
 WHEN ACTION_CD = '1422' THEN 'Referral'
 WHEN ACTION_CD = '1407' THEN 'AG Request'
 WHEN ACTION_CD = '1608' THEN 'RAS Request'
 END AS 'Referral Type'
 ,PROVIDER_ORG_ID
 ,SPECIALTY_DESC
 ,'East Kent Hospitals Foundation Trust' AS 'Provider'

FROM [Table] R

WHERE SPECIALTY_DESC = 'Dermatology'
AND PROVIDER_ORG_ID = 'RVV'

ORDER BY R.UBRN_ID, CONVERT(date,ACTION_DT_TM) DESC


-- exploration of dates with very high referral numbers 
SELECT 
*
FROM [Table] R
WHERE SPECIALTY_DESC = 'Dermatology'
AND PROVIDER_ORG_ID = 'RVV'
AND CONVERT(date,ACTION_DT_TM) = '20231019'


-- three hospitals are way higher QEH, Ashford, KCH Cantebury

SELECT 
SERVICE_NAME
,COUNT(UBRN_ID)
FROM [Table] R
WHERE SPECIALTY_DESC = 'Dermatology'
AND PROVIDER_ORG_ID = 'RVV'
AND CONVERT(date,ACTION_DT_TM) = '20230717'
GROUP BY SERVICE_NAME

SELECT 
SERVICE_NAME
,COUNT(UBRN_ID)
FROM [Table] R
WHERE SPECIALTY_DESC = 'Dermatology'
AND PROVIDER_ORG_ID = 'RVV'
AND CONVERT(date,ACTION_DT_TM) = '20231018'
GROUP BY SERVICE_NAME



-- Look at clinician's - no anomaly

SELECT 
REFERRING_CLINICIAN_ID
,COUNT(UBRN_ID)
FROM [Table] R
WHERE SPECIALTY_DESC = 'Dermatology'
AND PROVIDER_ORG_ID = 'RVV'
AND CONVERT(date,ACTION_DT_TM) = '20230717'
GROUP BY REFERRING_CLINICIAN_ID
ORDER BY COUNT(UBRN_ID)

-- Look at referrer - no anomaly

SELECT 
REFERRER_ORG_NAME
,COUNT(UBRN_ID)
FROM [Table] R
WHERE SPECIALTY_DESC = 'Dermatology'
AND PROVIDER_ORG_ID = 'RVV'
AND CONVERT(date,ACTION_DT_TM) = '20231019'
GROUP BY REFERRER_ORG_NAME
ORDER BY COUNT(UBRN_ID) DESC

-- look at record id - no duplicates

SELECT 
RECORD_ID
,COUNT(UBRN_ID)
FROM [Table] R
WHERE SPECIALTY_DESC = 'Dermatology'
AND PROVIDER_ORG_ID = 'RVV'
AND CONVERT(date,ACTION_DT_TM) = '20231019'
GROUP BY RECORD_ID
ORDER BY COUNT(UBRN_ID) DESC

-- Check UBRN distinct
SELECT DISTINCT INITIAL_UBRN_ID
FROM [Table] R
WHERE SPECIALTY_DESC = 'Dermatology'
AND PROVIDER_ORG_ID = 'RVV'
AND CONVERT(date,ACTION_DT_TM) = '20231019'

-- check patient's are distinct

SELECT 
PATIENTS_REG_GP_PRACTICE_NAME
,COUNT(UBRN_ID)
FROM [Table] R
WHERE SPECIALTY_DESC = 'Dermatology'
AND PROVIDER_ORG_ID = 'RVV'
AND CONVERT(date,ACTION_DT_TM) = '20231019'
GROUP BY PATIENTS_REG_GP_PRACTICE_NAME
ORDER BY COUNT(UBRN_ID) DESC

SELECT *
,R.ACTION_DT_TM
,ACTION_REASON_DESC

FROM [Table] R
WHERE UBRN_ID = '9ae3d923-400f-4425-8926-b7ea55821cd1'
ORDER BY R.ACTION_DT_TM 

SELECT 
E_REFERRAL_PATHWAY_START
,COUNT(UBRN_ID)
FROM [Table] R
WHERE SPECIALTY_DESC = 'Dermatology'
AND PROVIDER_ORG_ID = 'RVV'
GROUP BY E_REFERRAL_PATHWAY_START
ORDER BY COUNT(UBRN_ID) DESC
